// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfrjGwicU6ElQ3QqvgO0QRsb-sDKyCOBw',
    appId: '1:754541744480:web:c4cc868602d85a0c6c8e05',
    messagingSenderId: '754541744480',
    projectId: 'workout-app-428f4',
    authDomain: 'workout-app-428f4.firebaseapp.com',
    storageBucket: 'workout-app-428f4.appspot.com',
    measurementId: 'G-5YT749VJJR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMkqRvCAX0A0kxD59rM_ZuEBC58nZNmsE',
    appId: '1:754541744480:android:231716a7c0faddc56c8e05',
    messagingSenderId: '754541744480',
    projectId: 'workout-app-428f4',
    storageBucket: 'workout-app-428f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFAW7-qJqIDV2HA8pTzcPesoq88WnkRsU',
    appId: '1:754541744480:ios:5c657beb5047195a6c8e05',
    messagingSenderId: '754541744480',
    projectId: 'workout-app-428f4',
    storageBucket: 'workout-app-428f4.appspot.com',
    iosBundleId: 'com.example.workoutApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFAW7-qJqIDV2HA8pTzcPesoq88WnkRsU',
    appId: '1:754541744480:ios:5c657beb5047195a6c8e05',
    messagingSenderId: '754541744480',
    projectId: 'workout-app-428f4',
    storageBucket: 'workout-app-428f4.appspot.com',
    iosBundleId: 'com.example.workoutApp',
  );
}
